---
- include_tasks: remove_instance.yml

- name: Refresh hosts/inventory to remove old isntance
  meta: refresh_inventory

- name: Generate hosts file in terminate mode
  include_tasks: "../../provision_instances/tasks/generate_hosts.yml"
  vars:
    mode: "terminate"
