---
# Here you can add variables that will be available for all hosts.
ansible_python_interpreter: "python3"

region: northeurope
resource_group: DIDA-ABSN23-DV1673-H25-LP2 # Change me
domain_name: absn23.me # Change me

admin_email: absn23@student.bth.se

vmtags:
  StudentId: absn23 # Change me

pub_ssh_key_location: "/home/abed/.ssh/azure_microblog.pub" # Change me, your local ssh key!

server_user: "deploy"
server_user_pass: "$6$XftSV2Q0TJTxcVG5$QRmDf/kYi/M0tjuGStimxIznrqQbwDW8B7VXraMyfp65cgmVmlyOS28IBnqKmQsuQwPL5eAmCPiKhJBoRGCOK/" # change me
server_user_groups:
  - sudo
