apiVersion: apps/v1
kind: Deployment
metadata:
  name: microblog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microblog
  template:
    metadata:
      labels:
        app: microblog
    spec:
      containers:
        - name: microblog
          image: abedsandeed/microblog:prod
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
          ports:
            - containerPort: 5000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: microblog-secrets
                  key: SECRET_KEY
            - name: DATABASE_URL
              value: "mysql+pymysql://microblog:pass@mysql/microblog"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: DB_PASSWORD
