name: Security Scan

on:
  push:
  workflow_call:

jobs:
  security:
    name: Run security scanners
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: microblog:prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit
        run: |
          bandit -r app

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME -f docker/Dockerfile_prod .

      - name: Run Trivy image scan
        run: docker run -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image --scanners vuln,secret,misconfig --no-progress --severity HIGH,CRITICAL --exit-code 1 $IMAGE_NAME

      - name: Run Trivy filesystem scan
        run: docker run --rm -v .:/repo -w /repo aquasec/trivy:latest fs --scanners vuln,secret,misconfig --severity HIGH,CRITICAL --exit-code 1 --no-progress --skip-dirs .venv,venv .

      - name: Run Dockle
        run: |
          VERSION=$(curl -s https://api.github.com/repos/goodwithtech/dockle/releases/latest | \
            grep '"tag_name":' | \
            sed -E 's/.*"v([^"]+)".*/\1/')
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
            goodwithtech/dockle:v${VERSION} --ignore DKL-DI-0004 $IMAGE_NAME
          
